# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true  # push
          tags: netca.azurecr.io/samples/ca-one-app:latest

      - name: Connect to Server and Pull
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.PASSWORD }}
          command_timeout: 30m
          script: |
              sudo docker pull netca.azurecr.io/samples/ca-one-app:latest"

      # - name: Connect to Server and Pull
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USERNAME }}
      #     password: ${{ secrets.PASSWORD }}
      #     command_timeout: 30m
      #     script: |
      #         sudo docker stop ca-one-container
      #         sudo docker rm ca-one-container
      #         sudo docker run -d -p 3000:3000 --name ca-one-container  netca.azurecr.io/samples/ca-one-app:latest
      #         echo "ca-one-app container started"

      # sudo docker stop ca-one-container
      #         sudo docker rm ca-one-container
      #         sudo docker run -d -p 3000:3000 --name ca-one-container --restart unless-stopped netca.azurecr.io/samples/ca-one-app:latest
      #         echo "ca-one-app container started